# Generated by Django 5.2.8 on 2025-11-28 15:46

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cash",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10000.00"),
                help_text="Available cash balance for trading",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="cash balance",
            ),
        ),
    ]
