# Generated by Django 5.2.8 on 2025-12-25 17:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_supportrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("bot_created", "Bot Created"),
                            ("bot_updated", "Bot Updated"),
                            ("bot_deleted", "Bot Deleted"),
                            ("bot_activated", "Bot Activated"),
                            ("bot_deactivated", "Bot Deactivated"),
                            ("bot_executed", "Bot Executed"),
                            ("bot_execution_complete", "Bot Execution Complete"),
                            ("bot_trade_executed", "Bot Trade Executed"),
                            ("account_updated", "Account Updated"),
                            ("password_changed", "Password Changed"),
                            ("profile_updated", "Profile Updated"),
                            ("order_filled", "Order Filled"),
                            ("order_partial", "Order Partially Filled"),
                            ("order_cancelled", "Order Cancelled"),
                            ("system", "System Notification"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Type of notification",
                        max_length=50,
                        verbose_name="type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Notification title",
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Notification message", verbose_name="message"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the notification has been read",
                        verbose_name="is read",
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of related object (e.g., 'bot', 'order')",
                        max_length=50,
                        null=True,
                        verbose_name="related object type",
                    ),
                ),
                (
                    "related_object_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of related object",
                        null=True,
                        verbose_name="related object id",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional notification data",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="read at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who receives this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="users_notif_user_id_f3f50a_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="users_notif_user_id_c37f16_idx",
                    ),
                ],
            },
        ),
    ]
