# Generated by Django 5.2.8 on 2025-12-26 15:45

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_historicaluser_historicaluserprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin")],
                default="user",
                help_text="User role determines access permissions",
                max_length=20,
                verbose_name="role",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin")],
                default="user",
                help_text="User role determines access permissions",
                max_length=20,
                verbose_name="role",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("bot_created", "Bot Created"),
                            ("bot_updated", "Bot Updated"),
                            ("bot_deleted", "Bot Deleted"),
                            ("bot_activated", "Bot Activated"),
                            ("bot_deactivated", "Bot Deactivated"),
                            ("bot_executed", "Bot Executed"),
                            ("bot_execution_complete", "Bot Execution Complete"),
                            ("bot_trade_executed", "Bot Trade Executed"),
                            ("account_updated", "Account Updated"),
                            ("password_changed", "Password Changed"),
                            ("profile_updated", "Profile Updated"),
                            ("order_filled", "Order Filled"),
                            ("order_partial", "Order Partially Filled"),
                            ("order_cancelled", "Order Cancelled"),
                            ("system", "System Notification"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Type of notification",
                        max_length=50,
                        verbose_name="type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Notification title",
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Notification message", verbose_name="message"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the notification has been read",
                        verbose_name="is read",
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of related object (e.g., 'bot', 'order')",
                        max_length=50,
                        null=True,
                        verbose_name="related object type",
                    ),
                ),
                (
                    "related_object_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of related object",
                        null=True,
                        verbose_name="related object id",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional notification data",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="created at"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="read at"),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who receives this notification",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Notification",
                "verbose_name_plural": "historical Notifications",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSupportRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Contact email",
                        max_length=254,
                        verbose_name="email address",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="subject")),
                ("message", models.TextField(max_length=2000, verbose_name="message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="priority",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for admin use",
                        verbose_name="admin notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="updated at"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="resolved at"
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who submitted the request (optional for anonymous requests)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Support Request",
                "verbose_name_plural": "historical Support Requests",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
