# Generated by Django 5.2.8 on 2025-12-26 23:09

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_historicaluser_role_user_role_historicalnotification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluserprofile",
            name="cash",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Available cash balance for trading",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="cash balance",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="cash",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Available cash balance for trading",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="cash balance",
            ),
        ),
    ]
