# Generated by Django 5.2.8 on 2025-12-28 19:15

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stocks", "0012_add_period_days_to_bot_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BotSimulationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Simulation run name/identifier",
                        max_length=200,
                        verbose_name="name",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the simulation",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "data_split_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.80"),
                        help_text="Ratio for training data (default 0.80 = 80%)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.10")),
                            django.core.validators.MaxValueValidator(Decimal("0.90")),
                        ],
                        verbose_name="data split ratio",
                    ),
                ),
                (
                    "training_data_start",
                    models.DateField(
                        blank=True,
                        help_text="Start date for training data (80% of available data)",
                        null=True,
                        verbose_name="training data start",
                    ),
                ),
                (
                    "training_data_end",
                    models.DateField(
                        blank=True,
                        help_text="End date for training data",
                        null=True,
                        verbose_name="training data end",
                    ),
                ),
                (
                    "validation_data_start",
                    models.DateField(
                        blank=True,
                        help_text="Start date for validation data (20% of available data)",
                        null=True,
                        verbose_name="validation data start",
                    ),
                ),
                (
                    "validation_data_end",
                    models.DateField(
                        blank=True,
                        help_text="End date for validation data",
                        null=True,
                        verbose_name="validation data end",
                    ),
                ),
                (
                    "total_data_points",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of tick data points",
                        verbose_name="total data points",
                    ),
                ),
                (
                    "training_data_points",
                    models.IntegerField(
                        default=0,
                        help_text="Number of tick data points in training set",
                        verbose_name="training data points",
                    ),
                ),
                (
                    "validation_data_points",
                    models.IntegerField(
                        default=0,
                        help_text="Number of tick data points in validation set",
                        verbose_name="validation data points",
                    ),
                ),
                (
                    "total_bots",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of bot configurations to test",
                        verbose_name="total bots",
                    ),
                ),
                (
                    "config_ranges",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parameter ranges used for grid search",
                        verbose_name="config ranges",
                    ),
                ),
                (
                    "progress",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Simulation progress percentage (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="progress",
                    ),
                ),
                (
                    "current_day",
                    models.DateField(
                        blank=True,
                        help_text="Current day being processed",
                        null=True,
                        verbose_name="current day",
                    ),
                ),
                (
                    "bots_completed",
                    models.IntegerField(
                        default=0,
                        help_text="Number of bots completed",
                        verbose_name="bots completed",
                    ),
                ),
                (
                    "top_performers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Top performing bot configurations",
                        verbose_name="top performers",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if simulation failed",
                        verbose_name="error message",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="started at"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "stocks",
                    models.ManyToManyField(
                        help_text="Stocks to include in simulation",
                        related_name="simulation_runs",
                        to="stocks.stock",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot Simulation Run",
                "verbose_name_plural": "Bot Simulation Runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BotSimulationConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bot_index",
                    models.IntegerField(
                        help_text="Index of this bot in the simulation (0-based)",
                        verbose_name="bot index",
                    ),
                ),
                (
                    "config_json",
                    models.JSONField(
                        default=dict,
                        help_text="Complete bot configuration as JSON",
                        verbose_name="config json",
                    ),
                ),
                (
                    "use_social_analysis",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to use social media analysis",
                        verbose_name="use social analysis",
                    ),
                ),
                (
                    "use_news_analysis",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to use news analysis",
                        verbose_name="use news analysis",
                    ),
                ),
                (
                    "assigned_stocks",
                    models.ManyToManyField(
                        help_text="Stocks assigned to this bot",
                        related_name="simulation_configs",
                        to="stocks.stock",
                    ),
                ),
                (
                    "simulation_run",
                    models.ForeignKey(
                        help_text="Parent simulation run",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_configs",
                        to="bot_simulations.botsimulationrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot Simulation Config",
                "verbose_name_plural": "Bot Simulation Configs",
                "ordering": ["simulation_run", "bot_index"],
            },
        ),
        migrations.CreateModel(
            name="BotSimulationDay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Trading date", verbose_name="date"),
                ),
                (
                    "decisions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Decisions made for each stock (buy/sell/hold)",
                        verbose_name="decisions",
                    ),
                ),
                (
                    "actual_prices",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Actual prices for each stock on this day",
                        verbose_name="actual prices",
                    ),
                ),
                (
                    "performance_metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Daily performance metrics (profit, trades, etc.)",
                        verbose_name="performance metrics",
                    ),
                ),
                (
                    "signal_contributions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Which signals contributed to each decision",
                        verbose_name="signal contributions",
                    ),
                ),
                (
                    "simulation_config",
                    models.ForeignKey(
                        help_text="Bot configuration for this day",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_results",
                        to="bot_simulations.botsimulationconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot Simulation Day",
                "verbose_name_plural": "Bot Simulation Days",
                "ordering": ["simulation_config", "date"],
                "indexes": [
                    models.Index(
                        fields=["simulation_config", "date"],
                        name="bot_simulat_simulat_fde2c5_idx",
                    ),
                    models.Index(fields=["date"], name="bot_simulat_date_7b7cc1_idx"),
                ],
                "unique_together": {("simulation_config", "date")},
            },
        ),
        migrations.CreateModel(
            name="BotSimulationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total profit/loss in USD",
                        max_digits=15,
                        verbose_name="total profit",
                    ),
                ),
                (
                    "total_trades",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of trades executed",
                        verbose_name="total trades",
                    ),
                ),
                (
                    "winning_trades",
                    models.IntegerField(
                        default=0,
                        help_text="Number of profitable trades",
                        verbose_name="winning trades",
                    ),
                ),
                (
                    "losing_trades",
                    models.IntegerField(
                        default=0,
                        help_text="Number of losing trades",
                        verbose_name="losing trades",
                    ),
                ),
                (
                    "win_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Win rate percentage (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="win rate",
                    ),
                ),
                (
                    "average_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average profit per trade",
                        max_digits=15,
                        verbose_name="average profit",
                    ),
                ),
                (
                    "average_loss",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average loss per trade",
                        max_digits=15,
                        verbose_name="average loss",
                    ),
                ),
                (
                    "max_drawdown",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Maximum drawdown in USD",
                        max_digits=15,
                        verbose_name="max drawdown",
                    ),
                ),
                (
                    "sharpe_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Sharpe ratio (risk-adjusted return)",
                        max_digits=10,
                        null=True,
                        verbose_name="sharpe ratio",
                    ),
                ),
                (
                    "signal_productivity",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Analysis of which signals contributed to correct decisions. Format: {signal_type: {accuracy, true_positives, false_positives, contribution}}",
                        verbose_name="signal productivity",
                    ),
                ),
                (
                    "best_decisions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Best performing decisions with details",
                        verbose_name="best decisions",
                    ),
                ),
                (
                    "worst_decisions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Worst performing decisions with details",
                        verbose_name="worst decisions",
                    ),
                ),
                (
                    "final_cash",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Final cash balance",
                        max_digits=15,
                        verbose_name="final cash",
                    ),
                ),
                (
                    "final_portfolio_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Final total portfolio value",
                        max_digits=15,
                        verbose_name="final portfolio value",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "simulation_config",
                    models.OneToOneField(
                        help_text="Bot configuration for this result",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_result",
                        to="bot_simulations.botsimulationconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot Simulation Result",
                "verbose_name_plural": "Bot Simulation Results",
                "ordering": ["-total_profit"],
                "indexes": [
                    models.Index(
                        fields=["simulation_config"],
                        name="bot_simulat_simulat_49ba1c_idx",
                    ),
                    models.Index(
                        fields=["-total_profit"], name="bot_simulat_total_p_cbef09_idx"
                    ),
                    models.Index(
                        fields=["-win_rate"], name="bot_simulat_win_rat_fea601_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="botsimulationrun",
            index=models.Index(
                fields=["user", "status"], name="bot_simulat_user_id_62f6d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="botsimulationrun",
            index=models.Index(
                fields=["status", "created_at"], name="bot_simulat_status_6e94f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="botsimulationconfig",
            index=models.Index(
                fields=["simulation_run", "bot_index"],
                name="bot_simulat_simulat_e25441_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="botsimulationconfig",
            unique_together={("simulation_run", "bot_index")},
        ),
    ]
