# Generated by Django 5.2.8 on 2025-12-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_simulations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botsimulationrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                help_text="Current status of the simulation",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
