# Generated by Django 5.2.8 on 2025-12-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_simulations", "0002_add_paused_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="botsimulationrun",
            name="bot_execution_times",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Execution times in seconds for each completed bot (for ETA calculation)",
                verbose_name="bot execution times",
            ),
        ),
    ]
