# Generated by Django 5.2.8 on 2025-12-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_simulations", "0003_botsimulationrun_bot_execution_times"),
    ]

    operations = [
        migrations.AddField(
            model_name="botsimulationrun",
            name="execution_end_date",
            field=models.DateField(
                blank=True,
                help_text="End date when bot should stop executing trades",
                null=True,
                verbose_name="execution end date",
            ),
        ),
        migrations.AddField(
            model_name="botsimulationrun",
            name="execution_start_date",
            field=models.DateField(
                blank=True,
                help_text="Start date when bot should begin executing trades (daily execution)",
                null=True,
                verbose_name="execution start date",
            ),
        ),
    ]
