# Generated by Django 5.2.8 on 2025-12-29 01:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot_simulations", "0004_add_execution_dates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="botsimulationrun",
            name="data_split_ratio",
        ),
        migrations.RemoveField(
            model_name="botsimulationrun",
            name="training_data_end",
        ),
        migrations.RemoveField(
            model_name="botsimulationrun",
            name="training_data_start",
        ),
        migrations.RemoveField(
            model_name="botsimulationrun",
            name="validation_data_end",
        ),
        migrations.RemoveField(
            model_name="botsimulationrun",
            name="validation_data_start",
        ),
    ]
