# Generated by Django 5.2.8 on 2025-12-29 19:13

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_simulations", "0005_add_execution_dates2"),
    ]

    operations = [
        migrations.AddField(
            model_name="botsimulationconfig",
            name="current_date",
            field=models.DateField(
                blank=True,
                help_text="Current day being processed for this bot",
                null=True,
                verbose_name="current date",
            ),
        ),
        migrations.AddField(
            model_name="botsimulationconfig",
            name="current_tick_index",
            field=models.IntegerField(
                default=0,
                help_text="Current tick index within the current day",
                verbose_name="current tick index",
            ),
        ),
        migrations.AddField(
            model_name="botsimulationconfig",
            name="progress_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Progress percentage for this bot (0-100)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
                verbose_name="progress percentage",
            ),
        ),
        migrations.AddField(
            model_name="botsimulationconfig",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Current execution status of this bot",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.CreateModel(
            name="BotSimulationTick",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Trading date", verbose_name="date"),
                ),
                (
                    "tick_timestamp",
                    models.DateTimeField(
                        help_text="Exact timestamp of this tick",
                        verbose_name="tick timestamp",
                    ),
                ),
                (
                    "stock_symbol",
                    models.CharField(
                        help_text="Stock symbol for this tick",
                        max_length=20,
                        verbose_name="stock symbol",
                    ),
                ),
                (
                    "tick_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Price at this tick",
                        max_digits=15,
                        verbose_name="tick price",
                    ),
                ),
                (
                    "decision",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Buy/hold/sell decision with metadata (action, confidence, risk_score, position_size, reason)",
                        verbose_name="decision",
                    ),
                ),
                (
                    "signal_contributions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Which signals contributed to this decision (indicators, patterns, ML, social, news)",
                        verbose_name="signal contributions",
                    ),
                ),
                (
                    "portfolio_state",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Portfolio state at this tick (cash, positions, portfolio_value)",
                        verbose_name="portfolio state",
                    ),
                ),
                (
                    "cumulative_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cumulative profit/loss up to this tick",
                        max_digits=15,
                        verbose_name="cumulative profit",
                    ),
                ),
                (
                    "trade_executed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether a trade was executed at this tick",
                        verbose_name="trade executed",
                    ),
                ),
                (
                    "trade_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Trade execution details (action, quantity, price, cost/revenue)",
                        verbose_name="trade details",
                    ),
                ),
                (
                    "simulation_config",
                    models.ForeignKey(
                        help_text="Bot configuration for this tick",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tick_results",
                        to="bot_simulations.botsimulationconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot Simulation Tick",
                "verbose_name_plural": "Bot Simulation Ticks",
                "ordering": ["simulation_config", "date", "tick_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["simulation_config", "date"],
                        name="bot_simulat_simulat_e8e53e_idx",
                    ),
                    models.Index(
                        fields=["simulation_config", "date", "tick_timestamp"],
                        name="bot_simulat_simulat_f790ad_idx",
                    ),
                    models.Index(
                        fields=["date", "stock_symbol"],
                        name="bot_simulat_date_4c04ff_idx",
                    ),
                ],
            },
        ),
    ]
