export interface Indicator {
  id: string;
  name: string;
  category: "moving_average" | "bands" | "oscillator" | "other";
  defaultPeriod?: number;
  hasUpperLower?: boolean;
  color?: string;
  description?: string;
  analysis?: string;
}

export const AVAILABLE_INDICATORS: Indicator[] = [
  {
    id: "sma",
    name: "Simple Moving Average (SMA)",
    category: "moving_average",
    defaultPeriod: 20,
    color: "#3B82F6",
    description: "The average price over a specified period, giving equal weight to all prices.",
    analysis: "Price above SMA suggests uptrend; below suggests downtrend. Crossovers indicate potential trend changes. Use shorter periods (10-20) for short-term trends, longer (50-200) for long-term trends.",
  },
  {
    id: "ema",
    name: "Exponential Moving Average (EMA)",
    category: "moving_average",
    defaultPeriod: 20,
    color: "#10B981",
    description: "Similar to SMA but gives more weight to recent prices, making it more responsive to price changes.",
    analysis: "More sensitive than SMA. When price crosses above EMA, it's bullish; below is bearish. Golden cross (short EMA crosses above long EMA) indicates bullish trend. Death cross (short EMA crosses below long EMA) indicates bearish trend.",
  },
  {
    id: "wma",
    name: "Weighted Moving Average (WMA)",
    category: "moving_average",
    defaultPeriod: 20,
    color: "#F59E0B",
    description: "Assigns more weight to recent prices using a linear weighting scheme.",
    analysis: "More responsive than SMA but less than EMA. Useful for identifying short-term momentum. Price above WMA with rising WMA indicates strong uptrend.",
  },
  {
    id: "dema",
    name: "Double Exponential Moving Average (DEMA)",
    category: "moving_average",
    defaultPeriod: 20,
    color: "#EF4444",
    description: "A faster-reacting moving average that reduces lag by applying EMA twice.",
    analysis: "Reduces lag compared to standard EMA. Useful for catching trend changes early. When DEMA crosses above price, it may signal a trend reversal. Works well in trending markets.",
  },
  {
    id: "tema",
    name: "Triple Exponential Moving Average (TEMA)",
    category: "moving_average",
    defaultPeriod: 20,
    color: "#8B5CF6",
    description: "Further reduces lag by applying EMA three times, making it very responsive to price changes.",
    analysis: "Most responsive moving average. Best for short-term trading and catching quick reversals. Price crossing above/below TEMA can signal immediate trend changes. Use with caution in choppy markets.",
  },
  {
    id: "tma",
    name: "Triangular Moving Average (TMA)",
    category: "moving_average",
    defaultPeriod: 20,
    color: "#06B6D4",
    description: "A double-smoothed moving average that applies SMA twice for a smoother line.",
    analysis: "Smoother than SMA, reducing false signals. Good for identifying long-term trends. Less sensitive to price fluctuations. Best used in trending markets to confirm trend direction.",
  },
  {
    id: "hma",
    name: "Hull Moving Average (HMA)",
    category: "moving_average",
    defaultPeriod: 20,
    color: "#F97316",
    description: "A fast and smooth moving average that uses weighted moving averages to reduce lag while maintaining smoothness.",
    analysis: "Combines speed and smoothness. Price above HMA indicates uptrend; below indicates downtrend. HMA turning up suggests bullish momentum; turning down suggests bearish momentum. Excellent for trend-following strategies.",
  },
  {
    id: "bollinger",
    name: "Bollinger Bands",
    category: "bands",
    defaultPeriod: 20,
    hasUpperLower: true,
    color: "#84CC16",
    description: "A volatility indicator consisting of a middle band (SMA) and two standard deviation bands above and below.",
    analysis: "Bands expand during high volatility and contract during low volatility. Price touching upper band may indicate overbought; lower band may indicate oversold. Squeeze (narrow bands) often precedes significant price moves. Price bouncing off bands can signal reversals.",
  },
  {
    id: "psar",
    name: "Parabolic SAR (PSAR)",
    category: "other",
    color: "#EC4899",
    description: "A trend-following indicator that shows potential reversal points in price direction.",
    analysis: "Dots below price indicate uptrend; above price indicate downtrend. When dots flip from below to above (or vice versa), it signals a potential trend reversal. Best used in trending markets, not choppy ones. Can help set trailing stop losses.",
  },
  {
    id: "supertrend",
    name: "Supertrend",
    category: "other",
    defaultPeriod: 10,
    color: "#14B8A6",
    description: "A trend-following indicator that combines ATR with price action to identify trend direction.",
    analysis: "Green line indicates uptrend; red line indicates downtrend. Line flipping from red to green signals bullish reversal; green to red signals bearish reversal. Price staying above (below) the line confirms trend strength. Works well in trending markets.",
  },
  {
    id: "alligator",
    name: "Alligator",
    category: "other",
    hasUpperLower: true,
    color: "#6366F1",
    description: "Three smoothed moving averages (Jaw, Teeth, Lips) that represent the 'alligator's mouth' to identify trends.",
    analysis: "When lines are intertwined (alligator sleeping), market is ranging. When lines separate and align (alligator eating), trend is active. Jaw (slowest) > Teeth > Lips indicates uptrend. Lips > Teeth > Jaw indicates downtrend. Trade in the direction of the alligator's mouth.",
  },
  {
    id: "ichimoku",
    name: "Ichimoku Cloud",
    category: "other",
    hasUpperLower: true,
    color: "#A855F7",
    description: "A comprehensive indicator showing support/resistance, trend direction, momentum, and buy/sell signals.",
    analysis: "Price above cloud = bullish; below cloud = bearish. Cloud thickness indicates support/resistance strength. Tenkan crossing above Kijun = bullish signal. Chikou above price = bullish; below = bearish. Senkou Span A/B form the cloud - watch for crossovers. Best used as a complete system, not individual components.",
  },
  {
    id: "atr_trailing",
    name: "ATR Trailing Stop Loss",
    category: "other",
    defaultPeriod: 14,
    color: "#F43F5E",
    description: "A dynamic stop-loss indicator based on Average True Range that adjusts to market volatility.",
    analysis: "Line below price in uptrend; above price in downtrend. When price crosses the line, it may signal a trend reversal or exit point. More volatile markets = wider stops. Use to manage risk and protect profits. Adjust multiplier for tighter/looser stops.",
  },
  {
    id: "donchian",
    name: "Donchian Channel",
    category: "bands",
    defaultPeriod: 20,
    hasUpperLower: true,
    color: "#22C55E",
    description: "A channel indicator showing the highest high and lowest low over a specified period.",
    analysis: "Upper band = highest high; lower band = lowest low. Price breaking above upper band may indicate breakout/continuation. Breaking below lower band may indicate breakdown. Channel width shows volatility. Middle line can act as support/resistance. Popular in breakout trading strategies.",
  },
  {
    id: "fractal",
    name: "Fractal Chaos Bands",
    category: "bands",
    defaultPeriod: 5,
    hasUpperLower: true,
    color: "#EAB308",
    description: "Bands based on fractal patterns that identify potential support and resistance levels.",
    analysis: "Upper band shows resistance; lower band shows support. Price bouncing off bands can signal reversals. Bands expand/contract with volatility. Useful for identifying entry/exit points. Works well in ranging markets. Combine with other indicators for confirmation.",
  },
  {
    id: "linear_regression",
    name: "Linear Regression Forecast",
    category: "other",
    defaultPeriod: 14,
    color: "#06B6D4",
    description: "A statistical indicator that forecasts future price based on linear regression of past prices.",
    analysis: "Shows expected price direction based on recent trend. Price above forecast = bullish momentum; below = bearish. Steeper slope = stronger trend. Can help identify when price deviates from expected path. Useful for mean reversion strategies.",
  },
  {
    id: "mcginley",
    name: "McGinley Dynamic Indicator",
    category: "moving_average",
    defaultPeriod: 14,
    color: "#8B5CF6",
    description: "A moving average that automatically adjusts to market speed, reducing whipsaws and false signals.",
    analysis: "Adapts to market volatility automatically. Price above MDI = uptrend; below = downtrend. Fewer false signals than traditional moving averages. Excellent for trend identification. Works well in both trending and ranging markets. Less lag than SMA/EMA.",
  },
  {
    id: "vwap",
    name: "Volume Weighted Average Price (VWAP)",
    category: "other",
    color: "#F97316",
    description: "The average price weighted by volume, showing the true average price at which a stock has traded.",
    analysis: "Price above VWAP = bullish; below = bearish. Institutional traders often use VWAP as a benchmark. Strong volume above VWAP confirms buying pressure. Price returning to VWAP can act as support/resistance. Best used intraday; resets each day. Useful for entry/exit timing.",
  },
  {
    id: "vwap_ma",
    name: "VWAP Moving Average",
    category: "moving_average",
    defaultPeriod: 20,
    color: "#EC4899",
    description: "A moving average of VWAP values, smoothing the VWAP line for trend analysis.",
    analysis: "Smoother than raw VWAP, reducing noise. Price above VWAP MA = bullish trend; below = bearish. Crossovers can signal trend changes. Useful for longer-term trend identification. Combines volume and price information. Less sensitive than VWAP but more reliable for trend following.",
  },
  {
    id: "keltner",
    name: "Keltner Channel",
    category: "bands",
    defaultPeriod: 20,
    hasUpperLower: true,
    color: "#14B8A6",
    description: "A volatility-based channel using EMA as the middle line and ATR for upper/lower bands.",
    analysis: "Similar to Bollinger Bands but uses ATR instead of standard deviation. Price touching upper band may indicate overbought; lower band may indicate oversold. Channel expansion = increased volatility. Squeeze (narrow channel) may precede breakouts. Price staying within channel suggests range-bound trading. Breakouts from channel can signal strong trends.",
  },
  {
    id: "rsi",
    name: "RSI",
    category: "oscillator",
    defaultPeriod: 14,
    color: "#F59E0B",
    description: "Relative Strength Index - A momentum oscillator that measures the speed and magnitude of price changes to identify overbought and oversold conditions.",
    analysis: "RSI above 70 typically indicates overbought conditions (potential sell signal); below 30 indicates oversold (potential buy signal). Divergences between RSI and price can signal trend reversals. RSI crossing above 50 in uptrend confirms strength; crossing below 50 in downtrend confirms weakness. Use with trend confirmation for best results.",
  },
  {
    id: "adx",
    name: "ADX",
    category: "oscillator",
    defaultPeriod: 14,
    color: "#8B5CF6",
    description: "Average Directional Index - Measures trend strength regardless of direction, helping identify when a trend is strong enough to trade.",
    analysis: "ADX above 25 indicates strong trend; below 20 suggests weak or ranging market. ADX doesn't show direction, only strength. Combine with +DI and -DI lines to determine trend direction. Rising ADX = strengthening trend; falling ADX = weakening trend. Best used to filter trades - only trade when ADX shows strong trend.",
  },
  {
    id: "cci",
    name: "Commodity Channel Index (CCI)",
    category: "oscillator",
    defaultPeriod: 20,
    color: "#EC4899",
    description: "Measures the variation of price from its statistical mean, identifying cyclical trends and overbought/oversold conditions.",
    analysis: "CCI above +100 indicates overbought conditions; below -100 indicates oversold. CCI crossing above +100 suggests strong upward momentum; crossing below -100 suggests strong downward momentum. Zero line crossovers can signal trend changes. Works well in trending markets. Use divergences to identify potential reversals.",
  },
  {
    id: "mfi",
    name: "Money Flow Index (MFI)",
    category: "oscillator",
    defaultPeriod: 14,
    color: "#10B981",
    description: "A volume-weighted RSI that combines price and volume to measure buying and selling pressure.",
    analysis: "MFI above 80 indicates overbought conditions; below 20 indicates oversold. More reliable than RSI because it includes volume. Divergences between MFI and price can signal reversals. MFI rising with price confirms uptrend; falling with price confirms downtrend. Use to confirm other indicators.",
  },
  {
    id: "macd",
    name: "MACD and MACD Signal",
    category: "oscillator",
    defaultPeriod: 12,
    color: "#3B82F6",
    description: "Moving Average Convergence Divergence - Shows the relationship between two moving averages and their signal line to identify momentum changes.",
    analysis: "MACD line crossing above signal line = bullish signal; crossing below = bearish signal. MACD crossing above zero line indicates bullish momentum; below zero indicates bearish. Histogram shows momentum strength - expanding histogram = strengthening trend. Divergences between MACD and price can signal reversals. One of the most popular momentum indicators.",
  },
  {
    id: "williams_r",
    name: "Williams %R",
    category: "oscillator",
    defaultPeriod: 14,
    color: "#F43F5E",
    description: "A momentum indicator that measures overbought and oversold levels, similar to Stochastic but inverted.",
    analysis: "Williams %R above -20 indicates overbought conditions (potential sell); below -80 indicates oversold (potential buy). The indicator is inverted (negative values). Look for divergences with price for reversal signals. Works well in ranging markets. Combine with trend confirmation for better accuracy.",
  },
  {
    id: "momentum",
    name: "Momentum Indicator (MOM)",
    category: "oscillator",
    defaultPeriod: 10,
    color: "#06B6D4",
    description: "Measures the rate of change in price by comparing current price to price N periods ago.",
    analysis: "Momentum above zero indicates upward momentum; below zero indicates downward momentum. Increasing momentum = accelerating trend; decreasing momentum = decelerating trend. Zero line crossovers can signal trend changes. Divergences between momentum and price can signal reversals. Useful for identifying trend strength and potential reversals.",
  },
  {
    id: "proc",
    name: "Price Rate Of Change (PROC)",
    category: "oscillator",
    defaultPeriod: 12,
    color: "#84CC16",
    description: "Measures the percentage change in price over a specified period, showing momentum and rate of price change.",
    analysis: "PROC above zero indicates positive momentum; below zero indicates negative momentum. Higher PROC values = stronger momentum. Zero line crossovers can signal trend changes. Divergences between PROC and price can signal reversals. Useful for identifying acceleration and deceleration in price movement.",
  },
  {
    id: "obv",
    name: "On Balance Volume (OBV)",
    category: "oscillator",
    color: "#22C55E",
    description: "A cumulative volume indicator that adds volume on up days and subtracts volume on down days to show volume flow.",
    analysis: "OBV rising confirms uptrend; falling confirms downtrend. Divergences between OBV and price can signal reversals - if price makes new highs but OBV doesn't, it may indicate weakness. OBV breaking above resistance = bullish; breaking below support = bearish. Volume precedes price, so OBV can lead price movements.",
  },
  {
    id: "bollinger_upper",
    name: "Bollinger Bands Upper (UBB)",
    category: "bands",
    defaultPeriod: 20,
    color: "#84CC16",
    description: "The upper band of Bollinger Bands, calculated as SMA plus two standard deviations. Part of the Bollinger Bands indicator system.",
    analysis: "Price touching or breaking above UBB may indicate overbought conditions. Strong breakouts above UBB can signal continuation of uptrend. Price bouncing off UBB can signal potential reversal. Works best when used with Middle Band (MBB) and Lower Band (LBB) for complete analysis.",
  },
  {
    id: "bollinger_middle",
    name: "Bollinger Bands Middle (MBB)",
    category: "bands",
    defaultPeriod: 20,
    color: "#84CC16",
    description: "The middle band of Bollinger Bands, which is a Simple Moving Average. Acts as the center line of the Bollinger Bands system.",
    analysis: "MBB acts as a dynamic support/resistance level. Price above MBB suggests bullish bias; below suggests bearish bias. MBB can act as a trend filter. Price crossing above/below MBB can signal trend changes. Works best when used with Upper Band (UBB) and Lower Band (LBB) for complete analysis.",
  },
  {
    id: "bollinger_lower",
    name: "Bollinger Bands Lower (LBB)",
    category: "bands",
    defaultPeriod: 20,
    color: "#84CC16",
    description: "The lower band of Bollinger Bands, calculated as SMA minus two standard deviations. Part of the Bollinger Bands indicator system.",
    analysis: "Price touching or breaking below LBB may indicate oversold conditions. Strong breakdowns below LBB can signal continuation of downtrend. Price bouncing off LBB can signal potential reversal. Works best when used with Middle Band (MBB) and Upper Band (UBB) for complete analysis.",
  },
  {
    id: "prev_n",
    name: "Prev N",
    category: "other",
    defaultPeriod: 1,
    color: "#6366F1",
    description: "A reference indicator that shows the price value from N periods ago, useful for comparing current price to historical levels.",
    analysis: "Use to compare current price to previous periods. Can help identify support/resistance levels from past prices. Useful for mean reversion strategies. Price returning to Prev N levels can act as support or resistance. Combine with other indicators for confirmation.",
  },
  {
    id: "nth_candle",
    name: "Nth Candle",
    category: "other",
    defaultPeriod: 1,
    color: "#A855F7",
    description: "A reference indicator that displays the price data from a specific candle position (Nth candle) in the past.",
    analysis: "Useful for comparing current price action to specific historical candles. Can help identify patterns and support/resistance levels. Useful for technical analysis of specific time periods. Combine with other indicators for comprehensive analysis.",
  },
  {
    id: "opening_range",
    name: "Opening Range",
    category: "other",
    color: "#F97316",
    description: "Shows the high and low of the first N minutes or periods of a trading session, used to identify key support and resistance levels.",
    analysis: "Opening range breakouts can signal strong directional moves. Price staying within opening range suggests consolidation. Breaking above opening range high = bullish; breaking below opening range low = bearish. Opening range often acts as support/resistance throughout the day. Popular in day trading strategies.",
  },
  {
    id: "number",
    name: "Number",
    category: "other",
    color: "#EAB308",
    description: "A numeric reference indicator that can be used for custom calculations, comparisons, or as a constant value in technical analysis.",
    analysis: "Useful for custom indicator calculations and comparisons. Can serve as a reference level for price action. Useful for creating custom trading strategies. Combine with other indicators for advanced analysis.",
  },
  {
    id: "signal_candle",
    name: "Signal Candle",
    category: "other",
    color: "#14B8A6",
    description: "Identifies and highlights specific candles that meet certain criteria, used to mark significant price action or pattern formations.",
    analysis: "Signal candles mark important price action events. Can indicate entry or exit points. Useful for identifying pattern formations. Combine with other technical analysis tools for confirmation. Signal candles often mark key reversal or continuation points.",
  },
  {
    id: "trade_candle",
    name: "Trade Candle",
    category: "other",
    color: "#EC4899",
    description: "Marks candles where trading signals are generated based on specific criteria, helping identify optimal entry and exit points.",
    analysis: "Trade candles indicate potential trading opportunities. Use to identify entry and exit points. Combine with risk management strategies. Trade candles should be confirmed with other indicators. Useful for systematic trading approaches.",
  },
  {
    id: "candle_time",
    name: "Candle Time",
    category: "other",
    color: "#06B6D4",
    description: "Displays the time information for each candle, useful for time-based analysis and identifying patterns at specific times of day.",
    analysis: "Useful for identifying time-based patterns and market behavior at specific times. Can help identify optimal trading hours. Useful for intraday trading strategies. Time-based analysis can reveal market inefficiencies. Combine with price action for comprehensive analysis.",
  },
];

export interface ChartPattern {
  id: string;
  name: string;
  signal: "bullish" | "bearish" | "neutral";
  color?: string;
  description?: string;
  analysis?: string;
}

export const AVAILABLE_CHART_PATTERNS: ChartPattern[] = [
  {
    id: "three_white_soldiers",
    name: "Three White Soldiers",
    signal: "bullish",
    color: "#10B981",
    description: "Strong bullish reversal pattern consisting of three consecutive bullish candles.",
    analysis: "Each candle closes higher than the previous, with small wicks. Indicates strong buying pressure and potential upward trend continuation. Best confirmed with volume increase.",
  },
  {
    id: "morning_doji_star",
    name: "Morning Doji Star",
    signal: "bullish",
    color: "#10B981",
    description: "Bullish reversal pattern with a bearish candle, doji, and bullish candle.",
    analysis: "The doji represents indecision after a downtrend. When followed by a bullish candle closing above the first candle's midpoint, it signals a potential reversal. High reliability pattern.",
  },
  {
    id: "abandoned_baby",
    name: "Abandoned Baby",
    signal: "bullish",
    color: "#10B981",
    description: "Strong bullish reversal pattern with gaps on both sides of a doji.",
    analysis: "Rare but highly reliable pattern. The gaps indicate strong momentum shift. Best used in downtrends to identify potential reversal points. Requires confirmation with volume.",
  },
  {
    id: "tri_star",
    name: "Tri Star",
    signal: "neutral",
    color: "#F59E0B",
    description: "Reversal pattern with three consecutive doji candles with gaps.",
    analysis: "Indicates extreme indecision in the market. The direction of the reversal depends on the overall trend. Watch for breakouts after this pattern forms.",
  },
  {
    id: "advance_block",
    name: "Advance Block",
    signal: "bearish",
    color: "#EF4444",
    description: "Bearish reversal pattern showing weakening upward momentum.",
    analysis: "Three bullish candles with decreasing body sizes and increasing wicks indicate buyers are losing strength. Often precedes a reversal or pullback.",
  },
  {
    id: "conceal_baby_swallow",
    name: "Conceal Baby Swallow",
    signal: "bullish",
    color: "#10B981",
    description: "Bullish continuation pattern with four candles showing bearish exhaustion.",
    analysis: "Rare pattern indicating bearish exhaustion. The small fourth candle suggests sellers are losing control. Look for bullish confirmation in the next candle.",
  },
  {
    id: "stick_sandwich",
    name: "Stick Sandwich",
    signal: "bullish",
    color: "#10B981",
    description: "Bullish reversal pattern with two bearish candles sandwiching a bullish one.",
    analysis: "The bullish candle in the middle suggests buyers are stepping in. When the third candle closes above both previous candles, it confirms the reversal.",
  },
  {
    id: "morning_star",
    name: "Morning Star",
    signal: "bullish",
    color: "#10B981",
    description: "Bullish reversal pattern with a bearish candle, small body, and bullish candle.",
    analysis: "Classic reversal pattern. The small middle candle represents indecision. When the third candle closes above the first candle's midpoint, it confirms the reversal.",
  },
  {
    id: "kicking",
    name: "Kicking",
    signal: "bullish",
    color: "#10B981",
    description: "Strong bullish reversal pattern with two marubozu candles and a gap.",
    analysis: "Very strong reversal signal. The gap between marubozu candles indicates a significant momentum shift. High reliability pattern, especially in downtrends.",
  },
  {
    id: "spinning_top",
    name: "Spinning Top",
    signal: "neutral",
    color: "#F59E0B",
    description: "Indecision pattern with a small body and long wicks on both sides.",
    analysis: "Indicates market uncertainty. The small body shows neither buyers nor sellers are in control. Often appears at potential reversal points. Wait for confirmation.",
  },
  {
    id: "engulfing",
    name: "Engulfing",
    signal: "bullish",
    color: "#10B981",
    description: "Reversal pattern where one candle completely engulfs the previous candle.",
    analysis: "Can be bullish or bearish depending on the direction. The engulfing candle shows strong momentum in the opposite direction. More reliable when it occurs after a strong trend.",
  },
  {
    id: "homing_pigeon",
    name: "Homing Pigeon",
    signal: "bullish",
    color: "#10B981",
    description: "Bullish reversal pattern with two bearish candles where the second is contained within the first.",
    analysis: "The second candle being smaller and contained suggests weakening bearish momentum. Often precedes a reversal, especially when it appears after a downtrend.",
  },
  {
    id: "head_and_shoulders",
    name: "Head and Shoulders",
    signal: "bearish",
    color: "#EF4444",
    description: "Reversal pattern indicating trend change from bullish to bearish. Consists of three peaks: left shoulder, higher head, and right shoulder at similar level.",
    analysis: "One of the most reliable reversal patterns. The three peaks form a head (highest) and two shoulders (lower and similar height). The neckline connects the two troughs between the peaks. When price breaks below the neckline with volume, it confirms the bearish reversal. The target is typically equal to the distance from the head to the neckline. Best used in uptrends to identify potential reversal points. Volume should decrease on the right shoulder compared to the left shoulder and head.",
  },
  {
    id: "double_top",
    name: "Double Top",
    signal: "bearish",
    color: "#EF4444",
    description: "Bearish reversal pattern with two peaks at similar levels, separated by a trough.",
    analysis: "A classic reversal pattern that forms after an uptrend. The two peaks should be at approximately the same price level, indicating strong resistance. The trough between them is called the neckline. When price breaks below the neckline with volume, it confirms the bearish reversal. The pattern is more reliable when: (1) the peaks are well-separated in time, (2) volume decreases on the second peak, (3) the second peak fails to exceed the first. The target is typically equal to the distance from the peaks to the neckline. Always wait for neckline break confirmation before entering a short position.",
  },
  {
    id: "double_bottom",
    name: "Double Bottom",
    signal: "bullish",
    color: "#10B981",
    description: "Bullish reversal pattern with two troughs at similar levels, separated by a peak.",
    analysis: "A reliable reversal pattern that forms after a downtrend. The two troughs should be at approximately the same price level, indicating strong support. The peak between them is called the neckline. When price breaks above the neckline with volume, it confirms the bullish reversal. The pattern is more reliable when: (1) the troughs are well-separated in time, (2) volume increases on the second trough, (3) the second trough doesn't go significantly lower than the first. The target is typically equal to the distance from the troughs to the neckline. Always wait for neckline break confirmation before entering a long position. This pattern is the bullish counterpart to the double top.",
  },
  {
    id: "flag",
    name: "Flag",
    signal: "bullish",
    color: "#10B981",
    description: "Continuation pattern that occurs after a sharp price movement. Consists of a flagpole (sharp move) followed by a flag (consolidation).",
    analysis: "A short-term continuation pattern that typically lasts 1-3 weeks. The flagpole is a sharp, almost vertical price move, followed by a rectangular consolidation area (the flag) that slopes against the trend. In a bullish flag, the flag slopes downward. The pattern is confirmed when price breaks out of the flag in the direction of the original move (flagpole). Volume should decrease during the flag formation and increase on the breakout. The target is typically measured by projecting the flagpole length from the breakout point. Flags are reliable continuation patterns and often occur in strong trending markets. The consolidation represents a brief pause before the trend resumes.",
  },
  {
    id: "pennant",
    name: "Pennant",
    signal: "bullish",
    color: "#10B981",
    description: "Continuation pattern with converging trend lines forming a small symmetrical triangle after a sharp price movement.",
    analysis: "Similar to a flag but with converging trend lines instead of parallel ones. The pennant forms after a sharp price move (the pole) and consists of a small symmetrical triangle. The pattern typically lasts 1-3 weeks. Volume should decrease during pennant formation and increase significantly on the breakout. The breakout should occur in the direction of the original trend (the pole). Pennants are more reliable when they form in the middle of a strong trend. The target is typically measured by projecting the pole length from the breakout point. Unlike flags, pennants have converging support and resistance lines, creating a triangle shape. This pattern indicates a brief consolidation before the trend continues.",
  },
  {
    id: "rising_wedge",
    name: "Rising Wedge",
    signal: "bearish",
    color: "#EF4444",
    description: "Bearish reversal pattern with both support and resistance lines sloping upward and converging, forming a wedge shape.",
    analysis: "A bearish reversal pattern that typically forms at the end of an uptrend. Both the support and resistance lines slope upward, but they converge, indicating weakening momentum. The pattern shows that each new high is less significant than the previous one, and each pullback is shallower. Volume typically decreases as the wedge forms, indicating lack of conviction. The breakdown usually occurs when price breaks below the lower trendline (support). The target is typically measured by projecting the height of the wedge from the breakdown point. Rising wedges are more reliable when they form after a significant uptrend. This pattern can also appear in downtrends as a continuation pattern, but it's more commonly a reversal pattern.",
  },
  {
    id: "falling_wedge",
    name: "Falling Wedge",
    signal: "bullish",
    color: "#10B981",
    description: "Bullish reversal pattern with both support and resistance lines sloping downward and converging, forming a wedge shape.",
    analysis: "A bullish reversal pattern that typically forms at the end of a downtrend. Both the support and resistance lines slope downward, but they converge, indicating weakening selling pressure. The pattern shows that each new low is less significant than the previous one, and each bounce is stronger. Volume typically decreases as the wedge forms, and increases on the breakout. The breakout usually occurs when price breaks above the upper trendline (resistance). The target is typically measured by projecting the height of the wedge from the breakout point. Falling wedges are more reliable when they form after a significant downtrend. This pattern can also appear in uptrends as a continuation pattern, but it's more commonly a reversal pattern. The converging lines indicate that sellers are losing control.",
  },
];
