# Generated by Django 5.2.8 on 2025-11-26 11:34

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Stock ticker symbol (e.g., AAPL, GOOGL)",
                        max_length=20,
                        unique=True,
                        verbose_name="symbol",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full company name",
                        max_length=200,
                        verbose_name="company name",
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        help_text="Stock exchange (e.g., NASDAQ, NYSE)",
                        max_length=50,
                        verbose_name="exchange",
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True,
                        help_text="Industry sector",
                        max_length=100,
                        verbose_name="sector",
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        help_text="Specific industry",
                        max_length=100,
                        verbose_name="industry",
                    ),
                ),
                (
                    "market_cap",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Market capitalization in USD",
                        null=True,
                        verbose_name="market capitalization",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Company description",
                        verbose_name="description",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "Stock",
                "verbose_name_plural": "Stocks",
                "ordering": ["symbol"],
                "indexes": [
                    models.Index(
                        fields=["symbol"], name="stocks_stoc_symbol_3e1bfd_idx"
                    ),
                    models.Index(
                        fields=["exchange"], name="stocks_stoc_exchang_2c4de0_idx"
                    ),
                    models.Index(
                        fields=["sector"], name="stocks_stoc_sector_6c2055_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("above", "Price Above"),
                            ("below", "Price Below"),
                            ("change_percent", "Percentage Change"),
                        ],
                        max_length=20,
                        verbose_name="alert type",
                    ),
                ),
                (
                    "threshold_value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Price or percentage threshold for the alert",
                        max_digits=12,
                        verbose_name="threshold value",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_triggered",
                    models.BooleanField(default=False, verbose_name="triggered"),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="triggered at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="stocks.stock",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Alert",
                "verbose_name_plural": "Stock Alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="stocks_stoc_user_id_c66cfe_idx",
                    ),
                    models.Index(
                        fields=["stock", "is_active"],
                        name="stocks_stoc_stock_i_1eb945_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Opening price for the trading period",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="open price",
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Highest price during the trading period",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="high price",
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Lowest price during the trading period",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="low price",
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Closing price for the trading period",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="close price",
                    ),
                ),
                (
                    "adjusted_close",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Adjusted closing price accounting for splits and dividends",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="adjusted close",
                    ),
                ),
                (
                    "volume",
                    models.BigIntegerField(
                        help_text="Number of shares traded",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="volume",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Trading date", verbose_name="date"),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("1d", "Daily"),
                            ("1h", "Hourly"),
                            ("5m", "5 Minutes"),
                            ("1m", "1 Minute"),
                        ],
                        default="1d",
                        max_length=5,
                        verbose_name="interval",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Price",
                "verbose_name_plural": "Stock Prices",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["stock", "date"], name="stocks_stoc_stock_i_86bebf_idx"
                    ),
                    models.Index(
                        fields=["stock", "interval", "date"],
                        name="stocks_stoc_stock_i_ccf070_idx",
                    ),
                    models.Index(fields=["date"], name="stocks_stoc_date_0355dc_idx"),
                ],
                "unique_together": {("stock", "date", "interval")},
            },
        ),
        migrations.CreateModel(
            name="UserWatchlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Personal notes about this stock",
                        verbose_name="notes",
                    ),
                ),
                (
                    "target_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Target price for alerts",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="target price",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchers",
                        to="stocks.stock",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Watchlist",
                "verbose_name_plural": "User Watchlists",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="stocks_user_user_id_53cb6b_idx",
                    ),
                    models.Index(
                        fields=["stock"], name="stocks_user_stock_i_80fd1b_idx"
                    ),
                ],
                "unique_together": {("user", "stock")},
            },
        ),
    ]
