# Generated by Django 5.2.8 on 2025-11-26 11:40

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntradayPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="open price",
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="high price",
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="low price",
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="close price",
                    ),
                ),
                (
                    "volume",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="volume",
                    ),
                ),
                (
                    "vwap",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Volume Weighted Average Price",
                        max_digits=12,
                        null=True,
                        verbose_name="VWAP",
                    ),
                ),
                (
                    "trade_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of trades in this period",
                        verbose_name="trade count",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="Start time of the interval", verbose_name="timestamp"
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("1m", "1 Minute"),
                            ("30s", "30 Seconds"),
                            ("15s", "15 Seconds"),
                            ("10s", "10 Seconds"),
                            ("5s", "5 Seconds"),
                            ("1s", "1 Second"),
                        ],
                        default="1m",
                        max_length=5,
                        verbose_name="interval",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("pre_market", "Pre-Market"),
                            ("regular", "Regular Hours"),
                            ("after_hours", "After Hours"),
                        ],
                        default="regular",
                        max_length=20,
                        verbose_name="session type",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "Intraday Price",
                "verbose_name_plural": "Intraday Prices",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="StockTick",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Price at this tick",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="price",
                    ),
                ),
                (
                    "volume",
                    models.BigIntegerField(
                        help_text="Volume traded at this price",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="volume",
                    ),
                ),
                (
                    "bid_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Best bid price",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="bid price",
                    ),
                ),
                (
                    "ask_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Best ask price",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="ask price",
                    ),
                ),
                (
                    "bid_size",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Volume at bid price",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="bid size",
                    ),
                ),
                (
                    "ask_size",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Volume at ask price",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="ask size",
                    ),
                ),
                (
                    "trade_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("buy", "Buy"),
                            ("sell", "Sell"),
                            ("market", "Market"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="trade type",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="Exact timestamp of the tick",
                        verbose_name="timestamp",
                    ),
                ),
                (
                    "is_market_hours",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this tick occurred during market hours",
                        verbose_name="market hours",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "Stock Tick",
                "verbose_name_plural": "Stock Ticks",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="stockprice",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="stockprice",
            name="timestamp",
            field=models.DateTimeField(
                blank=True,
                help_text="Exact timestamp for intraday data",
                null=True,
                verbose_name="timestamp",
            ),
        ),
        migrations.AlterField(
            model_name="stockprice",
            name="interval",
            field=models.CharField(
                choices=[
                    ("1d", "Daily"),
                    ("4h", "4 Hours"),
                    ("1h", "Hourly"),
                    ("30m", "30 Minutes"),
                    ("15m", "15 Minutes"),
                    ("5m", "5 Minutes"),
                    ("1m", "1 Minute"),
                    ("30s", "30 Seconds"),
                    ("15s", "15 Seconds"),
                    ("5s", "5 Seconds"),
                    ("1s", "1 Second"),
                ],
                default="1d",
                max_length=5,
                verbose_name="interval",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stockprice",
            unique_together={("stock", "date", "timestamp", "interval")},
        ),
        migrations.AddIndex(
            model_name="stockprice",
            index=models.Index(
                fields=["stock", "timestamp"], name="stocks_stoc_stock_i_63cdc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockprice",
            index=models.Index(
                fields=["stock", "interval", "timestamp"],
                name="stocks_stoc_stock_i_e32355_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockprice",
            index=models.Index(
                fields=["timestamp"], name="stocks_stoc_timesta_7a363a_idx"
            ),
        ),
        migrations.AddField(
            model_name="intradayprice",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intraday_prices",
                to="stocks.stock",
            ),
        ),
        migrations.AddField(
            model_name="stocktick",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticks",
                to="stocks.stock",
            ),
        ),
        migrations.AddIndex(
            model_name="intradayprice",
            index=models.Index(
                fields=["stock", "timestamp"], name="stocks_intr_stock_i_7d8eb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intradayprice",
            index=models.Index(
                fields=["stock", "interval", "timestamp"],
                name="stocks_intr_stock_i_30b100_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="intradayprice",
            index=models.Index(
                fields=["stock", "session_type", "timestamp"],
                name="stocks_intr_stock_i_f47bfe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="intradayprice",
            index=models.Index(
                fields=["timestamp"], name="stocks_intr_timesta_f64a08_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="intradayprice",
            unique_together={("stock", "timestamp", "interval")},
        ),
        migrations.AddIndex(
            model_name="stocktick",
            index=models.Index(
                fields=["stock", "timestamp"], name="stocks_stoc_stock_i_9aa5aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktick",
            index=models.Index(
                fields=["stock", "is_market_hours", "timestamp"],
                name="stocks_stoc_stock_i_9812a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stocktick",
            index=models.Index(
                fields=["timestamp"], name="stocks_stoc_timesta_0f1adf_idx"
            ),
        ),
    ]
