# Generated by Django 5.2.8 on 2025-11-28 13:21

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_intradayprice_stocktick_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Number of shares purchased', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='quantity')),
                ('purchase_price', models.DecimalField(decimal_places=4, help_text='Price per share at purchase', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='purchase price')),
                ('purchase_date', models.DateField(help_text='Date when the stock was purchased', verbose_name='purchase date')),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this holding', verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_holders', to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'ordering': ['-purchase_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'purchase_date'], name='stocks_port_user_id_d3b152_idx'), models.Index(fields=['stock'], name='stocks_port_stock_i_fd521b_idx'), models.Index(fields=['user', 'stock'], name='stocks_port_user_id_1cf5a4_idx')],
            },
        ),
    ]
