# Generated by Django 5.2.8 on 2025-12-25 15:05

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0006_alter_order_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingBotConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Bot name/identifier",
                        max_length=200,
                        verbose_name="name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Is bot active", verbose_name="active"
                    ),
                ),
                (
                    "budget_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash Budget"),
                            ("portfolio", "Portfolio Budget"),
                        ],
                        default="cash",
                        help_text="Type of budget assignment: cash or portfolio",
                        max_length=20,
                        verbose_name="budget type",
                    ),
                ),
                (
                    "budget_cash",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cash budget amount (if budget_type is 'cash')",
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="budget cash",
                    ),
                ),
                (
                    "max_position_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Maximum position size per trade",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="max position size",
                    ),
                ),
                (
                    "max_daily_trades",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum trades per day",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="max daily trades",
                    ),
                ),
                (
                    "max_daily_loss",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum loss threshold per day",
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="max daily loss",
                    ),
                ),
                (
                    "risk_per_trade",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.00"),
                        help_text="Risk percentage per trade (0.01-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="risk per trade",
                    ),
                ),
                (
                    "stop_loss_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Stop loss percentage (0.01-100)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="stop loss percent",
                    ),
                ),
                (
                    "take_profit_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Take profit percentage (0.01-100)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="take profit percent",
                    ),
                ),
                (
                    "enabled_indicators",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Indicator configurations (JSON)",
                        verbose_name="enabled indicators",
                    ),
                ),
                (
                    "enabled_patterns",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Pattern configurations (JSON)",
                        verbose_name="enabled patterns",
                    ),
                ),
                (
                    "buy_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Buy condition rules (JSON)",
                        verbose_name="buy rules",
                    ),
                ),
                (
                    "sell_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Sell condition rules (JSON)",
                        verbose_name="sell rules",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "assigned_stocks",
                    models.ManyToManyField(
                        help_text="Stock symbols in which bot can operate (REQUIRED)",
                        related_name="bot_configs",
                        to="stocks.stock",
                    ),
                ),
                (
                    "budget_portfolio",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Existing portfolio positions assigned to bot (if budget_type is 'portfolio')",
                        related_name="bot_configs",
                        to="stocks.portfolio",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trading_bots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trading Bot Config",
                "verbose_name_plural": "Trading Bot Configs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="bot_config",
            field=models.ForeignKey(
                blank=True,
                help_text="Trading bot that created this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="stocks.tradingbotconfig",
            ),
        ),
        migrations.CreateModel(
            name="TradingBotExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell"), ("skip", "Skip")],
                        help_text="Action taken by bot: buy, sell, or skip",
                        max_length=10,
                        verbose_name="action",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Why the decision was made",
                        verbose_name="reason",
                    ),
                ),
                (
                    "indicators_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of indicators at decision time",
                        verbose_name="indicators data",
                    ),
                ),
                (
                    "patterns_detected",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Patterns found at decision time",
                        verbose_name="patterns detected",
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calculated risk score (0-100)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="risk score",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="timestamp"),
                ),
                (
                    "bot_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="stocks.tradingbotconfig",
                    ),
                ),
                (
                    "executed_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Order created if trade was executed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bot_executions",
                        to="stocks.order",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_executions",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trading Bot Execution",
                "verbose_name_plural": "Trading Bot Executions",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="tradingbotconfig",
            index=models.Index(
                fields=["user", "is_active"], name="stocks_trad_user_id_b1d3a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tradingbotconfig",
            index=models.Index(
                fields=["is_active", "created_at"],
                name="stocks_trad_is_acti_ccb8b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tradingbotexecution",
            index=models.Index(
                fields=["bot_config", "timestamp"],
                name="stocks_trad_bot_con_eaa580_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tradingbotexecution",
            index=models.Index(
                fields=["stock", "timestamp"], name="stocks_trad_stock_i_826ff9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tradingbotexecution",
            index=models.Index(
                fields=["action", "timestamp"], name="stocks_trad_action_01a54a_idx"
            ),
        ),
    ]
