# Generated by Django 5.2.8 on 2025-12-26 12:22

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0007_tradingbotconfig_order_bot_config_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalStock",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "symbol",
                    models.CharField(
                        db_index=True,
                        help_text="Stock ticker symbol (e.g., AAPL, GOOGL)",
                        max_length=20,
                        verbose_name="symbol",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full company name",
                        max_length=200,
                        verbose_name="company name",
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        help_text="Stock exchange (e.g., NASDAQ, NYSE)",
                        max_length=50,
                        verbose_name="exchange",
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True,
                        help_text="Industry sector",
                        max_length=100,
                        verbose_name="sector",
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        help_text="Specific industry",
                        max_length=100,
                        verbose_name="industry",
                    ),
                ),
                (
                    "market_cap",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Market capitalization in USD",
                        null=True,
                        verbose_name="market capitalization",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Company description",
                        verbose_name="description",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="updated at"
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Stock",
                "verbose_name_plural": "historical Stocks",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
