# Generated by Django 5.2.8 on 2025-12-26 16:18

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0008_historicalstock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="News source name",
                        max_length=200,
                        verbose_name="name",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("api", "API"), ("scraper", "Web Scraper")],
                        help_text="Type of news source",
                        max_length=20,
                        verbose_name="source type",
                    ),
                ),
                (
                    "api_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="API configuration (keys, endpoints, etc.)",
                        verbose_name="api config",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is source active",
                        verbose_name="active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "News Source",
                "verbose_name_plural": "News Sources",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SocialMediaSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Social media source name",
                        max_length=200,
                        verbose_name="name",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("twitter", "Twitter"),
                            ("reddit", "Reddit"),
                            ("stocktwits", "StockTwits"),
                            ("other", "Other"),
                        ],
                        help_text="Social media platform",
                        max_length=20,
                        verbose_name="platform",
                    ),
                ),
                (
                    "api_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="API configuration (keys, endpoints, etc.)",
                        verbose_name="api config",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is source active",
                        verbose_name="active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "Social Media Source",
                "verbose_name_plural": "Social Media Sources",
                "ordering": ["platform", "name"],
            },
        ),
        migrations.AddField(
            model_name="tradingbotconfig",
            name="enable_news_analysis",
            field=models.BooleanField(
                default=False,
                help_text="Enable news sentiment analysis",
                verbose_name="enable news analysis",
            ),
        ),
        migrations.AddField(
            model_name="tradingbotconfig",
            name="enable_social_analysis",
            field=models.BooleanField(
                default=False,
                help_text="Enable social media sentiment analysis",
                verbose_name="enable social analysis",
            ),
        ),
        migrations.AddField(
            model_name="tradingbotconfig",
            name="enabled_ml_models",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of ML model IDs to use",
                verbose_name="enabled ml models",
            ),
        ),
        migrations.AddField(
            model_name="tradingbotconfig",
            name="ml_model_weights",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Weights for each ML model (model_id: weight)",
                verbose_name="ml model weights",
            ),
        ),
        migrations.AddField(
            model_name="tradingbotconfig",
            name="risk_adjustment_factor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.40"),
                help_text="How much risk reduces signal confidence (0-1)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MinValueValidator(Decimal("1.00")),
                ],
                verbose_name="risk adjustment factor",
            ),
        ),
        migrations.AddField(
            model_name="tradingbotconfig",
            name="risk_based_position_scaling",
            field=models.BooleanField(
                default=True,
                help_text="Automatically reduce position size when risk score is high",
                verbose_name="risk based position scaling",
            ),
        ),
        migrations.AddField(
            model_name="tradingbotconfig",
            name="risk_score_threshold",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum risk score to allow trading (0-100)",
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="risk score threshold",
            ),
        ),
        migrations.AddField(
            model_name="tradingbotconfig",
            name="signal_aggregation_method",
            field=models.CharField(
                choices=[
                    ("weighted_average", "Weighted Average"),
                    ("ensemble_voting", "Ensemble Voting"),
                    ("threshold_based", "Threshold Based"),
                    ("custom_rule", "Custom Rule"),
                ],
                default="weighted_average",
                help_text="Method to combine multiple signals",
                max_length=20,
                verbose_name="signal aggregation method",
            ),
        ),
        migrations.AddField(
            model_name="tradingbotconfig",
            name="signal_thresholds",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Minimum thresholds for signals (confidence, strength, count)",
                verbose_name="signal thresholds",
            ),
        ),
        migrations.AddField(
            model_name="tradingbotconfig",
            name="signal_weights",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Weights for each signal type (ml, indicators, patterns, social, news)",
                verbose_name="signal weights",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")],
                        default="buy",
                        help_text="Type of transaction: buy or sell",
                        max_length=4,
                        verbose_name="transaction type",
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("market", "Market Order - Execute at current price"),
                            (
                                "target",
                                "Target Order - Execute when price reaches target",
                            ),
                        ],
                        default="market",
                        help_text="Type of order: market (immediate) or target (conditional)",
                        max_length=10,
                        verbose_name="order type",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Number of shares to purchase",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "target_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Target price for conditional orders (only for target orders)",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="target price",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                            ("insufficient_funds", "Insufficient Funds"),
                        ],
                        default="waiting",
                        help_text="Current status of the order",
                        max_length=25,
                        verbose_name="status",
                    ),
                ),
                (
                    "executed_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Price at which the order was executed",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="executed price",
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the order was executed",
                        null=True,
                        verbose_name="executed at",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Personal notes about this order",
                        verbose_name="notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="updated at"
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "bot_config",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Trading bot that created this order",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="stocks.tradingbotconfig",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="stocks.stock",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Order",
                "verbose_name_plural": "historical Orders",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPortfolio",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Number of shares purchased",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Price per share at purchase",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="purchase price",
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        help_text="Date when the stock was purchased",
                        verbose_name="purchase date",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Personal notes about this holding",
                        verbose_name="notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="updated at"
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The order that created this portfolio entry",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="stocks.order",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="stocks.stock",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Portfolio",
                "verbose_name_plural": "historical Portfolios",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTradingBotConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Bot name/identifier",
                        max_length=200,
                        verbose_name="name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Is bot active", verbose_name="active"
                    ),
                ),
                (
                    "budget_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash Budget"),
                            ("portfolio", "Portfolio Budget"),
                        ],
                        default="cash",
                        help_text="Type of budget assignment: cash or portfolio",
                        max_length=20,
                        verbose_name="budget type",
                    ),
                ),
                (
                    "budget_cash",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cash budget amount (if budget_type is 'cash')",
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="budget cash",
                    ),
                ),
                (
                    "max_position_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Maximum position size per trade",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="max position size",
                    ),
                ),
                (
                    "max_daily_trades",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum trades per day",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="max daily trades",
                    ),
                ),
                (
                    "max_daily_loss",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum loss threshold per day",
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="max daily loss",
                    ),
                ),
                (
                    "risk_per_trade",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.00"),
                        help_text="Risk percentage per trade (0.01-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="risk per trade",
                    ),
                ),
                (
                    "stop_loss_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Stop loss percentage (0.01-100)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="stop loss percent",
                    ),
                ),
                (
                    "take_profit_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Take profit percentage (0.01-100)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="take profit percent",
                    ),
                ),
                (
                    "enabled_ml_models",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of ML model IDs to use",
                        verbose_name="enabled ml models",
                    ),
                ),
                (
                    "ml_model_weights",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Weights for each ML model (model_id: weight)",
                        verbose_name="ml model weights",
                    ),
                ),
                (
                    "enable_social_analysis",
                    models.BooleanField(
                        default=False,
                        help_text="Enable social media sentiment analysis",
                        verbose_name="enable social analysis",
                    ),
                ),
                (
                    "enable_news_analysis",
                    models.BooleanField(
                        default=False,
                        help_text="Enable news sentiment analysis",
                        verbose_name="enable news analysis",
                    ),
                ),
                (
                    "signal_aggregation_method",
                    models.CharField(
                        choices=[
                            ("weighted_average", "Weighted Average"),
                            ("ensemble_voting", "Ensemble Voting"),
                            ("threshold_based", "Threshold Based"),
                            ("custom_rule", "Custom Rule"),
                        ],
                        default="weighted_average",
                        help_text="Method to combine multiple signals",
                        max_length=20,
                        verbose_name="signal aggregation method",
                    ),
                ),
                (
                    "signal_weights",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Weights for each signal type (ml, indicators, patterns, social, news)",
                        verbose_name="signal weights",
                    ),
                ),
                (
                    "signal_thresholds",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Minimum thresholds for signals (confidence, strength, count)",
                        verbose_name="signal thresholds",
                    ),
                ),
                (
                    "risk_score_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum risk score to allow trading (0-100)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="risk score threshold",
                    ),
                ),
                (
                    "risk_adjustment_factor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.40"),
                        help_text="How much risk reduces signal confidence (0-1)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MinValueValidator(Decimal("1.00")),
                        ],
                        verbose_name="risk adjustment factor",
                    ),
                ),
                (
                    "risk_based_position_scaling",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically reduce position size when risk score is high",
                        verbose_name="risk based position scaling",
                    ),
                ),
                (
                    "enabled_indicators",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Indicator configurations (JSON)",
                        verbose_name="enabled indicators",
                    ),
                ),
                (
                    "enabled_patterns",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Pattern configurations (JSON)",
                        verbose_name="enabled patterns",
                    ),
                ),
                (
                    "buy_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Buy condition rules (JSON)",
                        verbose_name="buy rules",
                    ),
                ),
                (
                    "sell_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Sell condition rules (JSON)",
                        verbose_name="sell rules",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="updated at"
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Trading Bot Config",
                "verbose_name_plural": "historical Trading Bot Configs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalUserWatchlist",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Personal notes about this stock",
                        verbose_name="notes",
                    ),
                ),
                (
                    "target_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Target price for alerts",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="target price",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="updated at"
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="stocks.stock",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical User Watchlist",
                "verbose_name_plural": "historical User Watchlists",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Model name/identifier",
                        max_length=200,
                        verbose_name="name",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("classification", "Classification"),
                            ("regression", "Regression"),
                        ],
                        help_text="Type of model: classification or regression",
                        max_length=20,
                        verbose_name="model type",
                    ),
                ),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("sklearn", "scikit-learn"),
                            ("pytorch", "PyTorch"),
                            ("tensorflow", "TensorFlow"),
                            ("custom", "Custom"),
                        ],
                        help_text="ML framework used",
                        max_length=20,
                        verbose_name="framework",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0",
                        help_text="Model version",
                        max_length=50,
                        verbose_name="version",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Model description",
                        verbose_name="description",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Model parameters and configuration (JSON)",
                        verbose_name="parameters",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is model active and available",
                        verbose_name="active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "ML Model",
                "verbose_name_plural": "ML Models",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "model_type"],
                        name="stocks_mlmo_is_acti_d5c822_idx",
                    ),
                    models.Index(
                        fields=["framework", "is_active"],
                        name="stocks_mlmo_framewo_343582_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BotSignalHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When analysis was performed",
                        verbose_name="timestamp",
                    ),
                ),
                (
                    "price_data_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of price data at analysis time",
                        verbose_name="price data snapshot",
                    ),
                ),
                (
                    "ml_signals",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="ML model predictions and signals",
                        verbose_name="ml signals",
                    ),
                ),
                (
                    "social_signals",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Social media sentiment signals",
                        verbose_name="social signals",
                    ),
                ),
                (
                    "news_signals",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="News sentiment signals",
                        verbose_name="news signals",
                    ),
                ),
                (
                    "indicator_signals",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Technical indicator signals",
                        verbose_name="indicator signals",
                    ),
                ),
                (
                    "pattern_signals",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Chart pattern signals",
                        verbose_name="pattern signals",
                    ),
                ),
                (
                    "aggregated_signal",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Combined signal after aggregation",
                        verbose_name="aggregated signal",
                    ),
                ),
                (
                    "final_decision",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell"), ("hold", "Hold")],
                        help_text="Final trading decision",
                        max_length=10,
                        verbose_name="final decision",
                    ),
                ),
                (
                    "decision_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Confidence in final decision (0-100)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="decision confidence",
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calculated risk score (0-100)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="risk score",
                    ),
                ),
                (
                    "bot_config",
                    models.ForeignKey(
                        help_text="Bot configuration that generated this signal",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signal_history",
                        to="stocks.tradingbotconfig",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related bot execution if trade was executed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signal_history",
                        to="stocks.tradingbotexecution",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        help_text="Stock being analyzed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signal_history",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot Signal History",
                "verbose_name_plural": "Bot Signal Histories",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["bot_config", "timestamp"],
                        name="stocks_bots_bot_con_f1d238_idx",
                    ),
                    models.Index(
                        fields=["stock", "timestamp"],
                        name="stocks_bots_stock_i_a0741d_idx",
                    ),
                    models.Index(
                        fields=["final_decision", "timestamp"],
                        name="stocks_bots_final_d_262958_idx",
                    ),
                ],
            },
        ),
    ]
