# Generated by Django 5.2.8 on 2025-12-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0009_add_ml_models_and_signal_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltradingbotconfig",
            name="indicator_thresholds",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom thresholds for indicator signals (overrides defaults). Format: {'rsi': {'oversold': 30, 'overbought': 70}, ...}",
                verbose_name="indicator thresholds",
            ),
        ),
        migrations.AddField(
            model_name="tradingbotconfig",
            name="indicator_thresholds",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom thresholds for indicator signals (overrides defaults). Format: {'rsi': {'oversold': 30, 'overbought': 70}, ...}",
                verbose_name="indicator thresholds",
            ),
        ),
    ]
