# Generated by Django 5.2.8 on 2025-12-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0010_add_indicator_thresholds"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingBotSettings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "default_indicator_thresholds",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default threshold values for all technical indicators. These values are used when bot configs don't specify custom thresholds.",
                        verbose_name="default indicator thresholds",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "Trading Bot Settings",
                "verbose_name_plural": "Trading Bot Settings",
            },
        ),
    ]
