# Generated by Django 5.2.8 on 2025-12-27 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0011_tradingbotsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltradingbotconfig",
            name="period_days",
            field=models.IntegerField(
                default=14,
                help_text="Number of days to look back for indicators and patterns calculation (1-365)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(365),
                ],
                verbose_name="period days",
            ),
        ),
        migrations.AddField(
            model_name="tradingbotconfig",
            name="period_days",
            field=models.IntegerField(
                default=14,
                help_text="Number of days to look back for indicators and patterns calculation (1-365)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(365),
                ],
                verbose_name="period days",
            ),
        ),
    ]
