# Generated by Django 5.2.8 on 2025-12-30 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0012_add_period_days_to_bot_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltradingbotconfig",
            name="signal_persistence_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tick_count", "Tick Count"),
                    ("time_duration", "Time Duration"),
                ],
                help_text="Type of signal persistence: tick_count (N ticks) or time_duration (M minutes). None means disabled (immediate execution).",
                max_length=20,
                null=True,
                verbose_name="signal persistence type",
            ),
        ),
        migrations.AddField(
            model_name="historicaltradingbotconfig",
            name="signal_persistence_value",
            field=models.IntegerField(
                blank=True,
                help_text="Persistence value: N for tick count or M for minutes. Required if signal_persistence_type is set.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="signal persistence value",
            ),
        ),
        migrations.AddField(
            model_name="tradingbotconfig",
            name="signal_persistence_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tick_count", "Tick Count"),
                    ("time_duration", "Time Duration"),
                ],
                help_text="Type of signal persistence: tick_count (N ticks) or time_duration (M minutes). None means disabled (immediate execution).",
                max_length=20,
                null=True,
                verbose_name="signal persistence type",
            ),
        ),
        migrations.AddField(
            model_name="tradingbotconfig",
            name="signal_persistence_value",
            field=models.IntegerField(
                blank=True,
                help_text="Persistence value: N for tick count or M for minutes. Required if signal_persistence_type is set.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="signal persistence value",
            ),
        ),
        migrations.AddField(
            model_name="tradingbotexecution",
            name="persistence_count",
            field=models.IntegerField(
                blank=True,
                help_text="Number of ticks or minutes that matched before execution",
                null=True,
                verbose_name="persistence count",
            ),
        ),
        migrations.AddField(
            model_name="tradingbotexecution",
            name="persistence_met",
            field=models.BooleanField(
                blank=True,
                help_text="Whether signal persistence criteria was met before execution",
                null=True,
                verbose_name="persistence met",
            ),
        ),
        migrations.AddField(
            model_name="tradingbotexecution",
            name="persistence_signal_history",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="History of signals during persistence period",
                verbose_name="persistence signal history",
            ),
        ),
    ]
