# Generated by Django 5.2.8 on 2025-12-31 10:34

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0013_add_signal_persistence_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalportfolio",
            name="bot_config",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Link to bot if created by bot (for shared view)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="stocks.tradingbotconfig",
            ),
        ),
        migrations.AddField(
            model_name="historicaltradingbotconfig",
            name="cash_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Current cash available to bot for trading",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="cash balance",
            ),
        ),
        migrations.AddField(
            model_name="historicaltradingbotconfig",
            name="initial_cash",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Initial cash allocation (for tracking)",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="initial cash",
            ),
        ),
        migrations.AddField(
            model_name="historicaltradingbotconfig",
            name="initial_portfolio_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Value of assigned portfolio at creation",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="initial portfolio value",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="bot_config",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to bot if created by bot (for shared view)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_portfolio_entries",
                to="stocks.tradingbotconfig",
            ),
        ),
        migrations.AddField(
            model_name="tradingbotconfig",
            name="cash_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Current cash available to bot for trading",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="cash balance",
            ),
        ),
        migrations.AddField(
            model_name="tradingbotconfig",
            name="initial_cash",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Initial cash allocation (for tracking)",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="initial cash",
            ),
        ),
        migrations.AddField(
            model_name="tradingbotconfig",
            name="initial_portfolio_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Value of assigned portfolio at creation",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="initial portfolio value",
            ),
        ),
        migrations.CreateModel(
            name="BotPortfolio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Current holding quantity (sum of all lots, must be integer)",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "average_purchase_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Weighted average purchase price across all lots",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="average purchase price",
                    ),
                ),
                (
                    "total_cost_basis",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total cost of all purchases for this position",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="total cost basis",
                    ),
                ),
                (
                    "first_purchase_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of first purchase for this position",
                        null=True,
                        verbose_name="first purchase date",
                    ),
                ),
                (
                    "last_purchase_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of most recent purchase for this position",
                        null=True,
                        verbose_name="last purchase date",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "bot_config",
                    models.ForeignKey(
                        help_text="Trading bot that owns this portfolio position",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_portfolio_holdings",
                        to="stocks.tradingbotconfig",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_portfolio_positions",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot Portfolio",
                "verbose_name_plural": "Bot Portfolios",
                "ordering": ["-last_purchase_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BotPortfolioLot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Quantity in this lot (must be integer, no fractional shares)",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Price per share for this lot",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="purchase price",
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        help_text="When this lot was purchased",
                        verbose_name="purchase date",
                    ),
                ),
                (
                    "remaining_quantity",
                    models.IntegerField(
                        help_text="Remaining quantity after any sells (must be integer)",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="remaining quantity",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "bot_portfolio",
                    models.ForeignKey(
                        help_text="Bot portfolio position this lot belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="stocks.botportfolio",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="The order that created this lot",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bot_portfolio_lot",
                        to="stocks.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot Portfolio Lot",
                "verbose_name_plural": "Bot Portfolio Lots",
                "ordering": ["-purchase_date", "-purchase_price"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalBotPortfolio",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Current holding quantity (sum of all lots, must be integer)",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "average_purchase_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Weighted average purchase price across all lots",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="average purchase price",
                    ),
                ),
                (
                    "total_cost_basis",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total cost of all purchases for this position",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="total cost basis",
                    ),
                ),
                (
                    "first_purchase_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of first purchase for this position",
                        null=True,
                        verbose_name="first purchase date",
                    ),
                ),
                (
                    "last_purchase_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of most recent purchase for this position",
                        null=True,
                        verbose_name="last purchase date",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="updated at"
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "bot_config",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Trading bot that owns this portfolio position",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="stocks.tradingbotconfig",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Bot Portfolio",
                "verbose_name_plural": "historical Bot Portfolios",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBotPortfolioLot",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Quantity in this lot (must be integer, no fractional shares)",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Price per share for this lot",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="purchase price",
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        help_text="When this lot was purchased",
                        verbose_name="purchase date",
                    ),
                ),
                (
                    "remaining_quantity",
                    models.IntegerField(
                        help_text="Remaining quantity after any sells (must be integer)",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="remaining quantity",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="updated at"
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "bot_portfolio",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Bot portfolio position this lot belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="stocks.botportfolio",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The order that created this lot",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="stocks.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Bot Portfolio Lot",
                "verbose_name_plural": "historical Bot Portfolio Lots",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name="botportfolio",
            index=models.Index(
                fields=["bot_config", "stock"], name="stocks_botp_bot_con_97ffe1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="botportfolio",
            index=models.Index(
                fields=["bot_config", "quantity"], name="stocks_botp_bot_con_c17ef7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="botportfolio",
            index=models.Index(fields=["stock"], name="stocks_botp_stock_i_00b1ef_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="botportfolio",
            unique_together={("bot_config", "stock")},
        ),
        migrations.AddIndex(
            model_name="botportfoliolot",
            index=models.Index(
                fields=["bot_portfolio", "purchase_price"],
                name="stocks_botp_bot_por_24a9dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="botportfoliolot",
            index=models.Index(
                fields=["bot_portfolio", "remaining_quantity"],
                name="stocks_botp_bot_por_eae36d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="botportfoliolot",
            index=models.Index(fields=["order"], name="stocks_botp_order_i_d69f6f_idx"),
        ),
    ]
