# Generated by Django 5.2.8 on 2025-12-31 10:34

from decimal import Decimal

from django.db import DatabaseError, migrations
from django.utils import timezone


def initialize_bot_portfolio_data(apps, schema_editor):
    """
    Data migration to:
    1. Initialize cash_balance for existing bots with budget_cash
    2. Create BotPortfolio and BotPortfolioLot entries for existing bot orders
    """
    TradingBotConfig = apps.get_model("stocks", "TradingBotConfig")
    Order = apps.get_model("stocks", "Order")
    BotPortfolio = apps.get_model("stocks", "BotPortfolio")
    BotPortfolioLot = apps.get_model("stocks", "BotPortfolioLot")
    Portfolio = apps.get_model("stocks", "Portfolio")

    # Initialize cash_balance for existing bots
    for bot_config in TradingBotConfig.objects.all():
        if bot_config.budget_cash and bot_config.cash_balance == Decimal("0.00"):
            bot_config.cash_balance = bot_config.budget_cash
            if not bot_config.initial_cash:
                bot_config.initial_cash = bot_config.budget_cash
            bot_config.save(update_fields=["cash_balance", "initial_cash"])

    # Create BotPortfolio and BotPortfolioLot entries for existing bot orders
    # Get all executed buy orders from bots
    bot_buy_orders = Order.objects.filter(
        bot_config__isnull=False,
        transaction_type="buy",
        status="done",
        executed_price__isnull=False,
    ).select_related("bot_config", "stock")

    for order in bot_buy_orders:
        try:
            # Get or create BotPortfolio entry
            bot_portfolio, created = BotPortfolio.objects.get_or_create(
                bot_config=order.bot_config,
                stock=order.stock,
                defaults={
                    "quantity": 0,
                    "average_purchase_price": Decimal("0.00"),
                    "total_cost_basis": Decimal("0.00"),
                },
            )

            # Calculate quantity as integer (round down)
            quantity = int(order.quantity)
            if quantity <= 0:
                continue

            # Calculate cost
            cost = quantity * order.executed_price

            # Update BotPortfolio
            if created:
                bot_portfolio.quantity = quantity
                bot_portfolio.average_purchase_price = order.executed_price
                bot_portfolio.total_cost_basis = cost
                bot_portfolio.first_purchase_date = (
                    order.executed_at.date()
                    if order.executed_at
                    else timezone.now().date()
                )
                bot_portfolio.last_purchase_date = (
                    order.executed_at.date()
                    if order.executed_at
                    else timezone.now().date()
                )
            else:
                # Calculate weighted average
                total_quantity = bot_portfolio.quantity + quantity
                total_cost = bot_portfolio.total_cost_basis + cost
                bot_portfolio.quantity = total_quantity
                bot_portfolio.average_purchase_price = (
                    total_cost / Decimal(str(total_quantity))
                    if total_quantity > 0
                    else Decimal("0.00")
                )
                bot_portfolio.total_cost_basis = total_cost
                if order.executed_at:
                    purchase_date = order.executed_at.date()
                    if not bot_portfolio.first_purchase_date:
                        bot_portfolio.first_purchase_date = purchase_date
                    bot_portfolio.last_purchase_date = purchase_date
            bot_portfolio.save()

            # Create BotPortfolioLot entry
            BotPortfolioLot.objects.get_or_create(
                bot_portfolio=bot_portfolio,
                order=order,
                defaults={
                    "quantity": quantity,
                    "purchase_price": order.executed_price,
                    "purchase_date": (
                        order.executed_at.date()
                        if order.executed_at
                        else timezone.now().date()
                    ),
                    "remaining_quantity": quantity,
                },
            )

            # Link Portfolio entry to bot if it exists
            try:
                portfolio_entry = Portfolio.objects.get(
                    user=order.user, stock=order.stock, order=order
                )
                portfolio_entry.bot_config = order.bot_config
                portfolio_entry.save(update_fields=["bot_config"])
            except Portfolio.DoesNotExist:
                pass
            except Portfolio.MultipleObjectsReturned:
                # If multiple, update the first one
                portfolio_entry = Portfolio.objects.filter(
                    user=order.user, stock=order.stock, order=order
                ).first()
                if portfolio_entry:
                    portfolio_entry.bot_config = order.bot_config
                    portfolio_entry.save(update_fields=["bot_config"])

        except (
            ValueError,
            AttributeError,
            KeyError,
            TypeError,
            OSError,
            DatabaseError,
        ) as e:
            # Log error but continue with other orders
            # Note: Using print in migration as logging may not be configured
            import sys

            sys.stderr.write(f"Error processing order {order.id}: {e}\n")
            continue


def reverse_migration(apps, schema_editor):
    """Reverse migration - remove BotPortfolio and BotPortfolioLot entries"""
    BotPortfolio = apps.get_model("stocks", "BotPortfolio")
    BotPortfolioLot = apps.get_model("stocks", "BotPortfolioLot")
    TradingBotConfig = apps.get_model("stocks", "TradingBotConfig")
    Portfolio = apps.get_model("stocks", "Portfolio")

    # Remove bot links from Portfolio
    Portfolio.objects.filter(bot_config__isnull=False).update(bot_config=None)

    # Delete BotPortfolioLot entries
    BotPortfolioLot.objects.all().delete()

    # Delete BotPortfolio entries
    BotPortfolio.objects.all().delete()

    # Reset cash_balance
    TradingBotConfig.objects.all().update(
        cash_balance=Decimal("0.00"), initial_cash=None, initial_portfolio_value=None
    )


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0014_add_bot_portfolio_models"),
    ]

    operations = [
        migrations.RunPython(initialize_bot_portfolio_data, reverse_migration),
    ]
