# Generated by Django 5.2.8 on 2025-12-31 11:06

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0015_initialize_bot_portfolio_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorder",
            name="quantity",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Number of shares to purchase (will be rounded to integer for execution)",
                max_digits=12,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0001"))
                ],
                verbose_name="quantity",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Number of shares to purchase (will be rounded to integer for execution)",
                max_digits=12,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0001"))
                ],
                verbose_name="quantity",
            ),
        ),
    ]
