# Generated by Django 5.2.8 on 2025-12-31 11:10

import django.core.validators
from django.db import migrations, models


def convert_portfolio_quantity_to_integer(apps, schema_editor):
    """Convert existing decimal quantity values to integers (rounding down)."""
    Portfolio = apps.get_model("stocks", "Portfolio")
    HistoricalPortfolio = apps.get_model("stocks", "HistoricalPortfolio")

    # Convert Portfolio quantities
    for portfolio in Portfolio.objects.all():
        if portfolio.quantity:
            # Round down to nearest integer (no fractional shares)
            portfolio.quantity = int(float(portfolio.quantity))
            portfolio.save(update_fields=["quantity"])

    # Convert HistoricalPortfolio quantities
    for historical in HistoricalPortfolio.objects.all():
        if historical.quantity:
            # Round down to nearest integer (no fractional shares)
            historical.quantity = int(float(historical.quantity))
            historical.save(update_fields=["quantity"])


def reverse_convert_portfolio_quantity(apps, schema_editor):
    """Reverse migration - convert integers back to decimals (not really needed, but for completeness)."""
    # This is a one-way migration, so we don't need to do anything


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0016_alter_historicalorder_quantity_alter_order_quantity"),
    ]

    operations = [
        migrations.RunPython(
            convert_portfolio_quantity_to_integer,
            reverse_convert_portfolio_quantity,
        ),
        migrations.AlterField(
            model_name="historicalportfolio",
            name="quantity",
            field=models.IntegerField(
                help_text="Number of shares purchased (must be integer, no fractional shares)",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="quantity",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="quantity",
            field=models.IntegerField(
                help_text="Number of shares purchased (must be integer, no fractional shares)",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="quantity",
            ),
        ),
    ]
